/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExercicioTres;

import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author Josmar
 */
public class PedraPapelTesoura extends javax.swing.JFrame {

    /**
     * Creates new form PedraPapelTesoura
     */
    public PedraPapelTesoura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pedraRad = new javax.swing.JRadioButton();
        papelRad = new javax.swing.JRadioButton();
        tesouraRad = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pedraRad.setText("Pedra");
        pedraRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedraRadActionPerformed(evt);
            }
        });

        papelRad.setText("Papel");
        papelRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papelRadActionPerformed(evt);
            }
        });

        tesouraRad.setText("Tesoura");
        tesouraRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesouraRadActionPerformed(evt);
            }
        });

        jLabel2.setText("Pedra, papel ou tesoura?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(pedraRad)
                    .addComponent(tesouraRad)
                    .addComponent(papelRad))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pedraRad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(papelRad)
                .addGap(3, 3, 3)
                .addComponent(tesouraRad)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pedraRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedraRadActionPerformed
        papelRad.setSelected(false);
        tesouraRad.setSelected(false);
        
        Random rn = new Random();
        int resposta = rn.nextInt(3);
                      
        if (pedraRad.isSelected() && resposta == 0) {
                          
            JOptionPane.showMessageDialog(this, "Tirei Papel, você perdeu!");
            }
        else if (pedraRad.isSelected() && resposta == 1) {
                          
            JOptionPane.showMessageDialog(this, "Tirei pedra, Empate!");
            }
        else if (pedraRad.isSelected() && resposta == 2) {
                          
            JOptionPane.showMessageDialog(this, "Tirei tesoura, Você ganhou!");
            }

    }//GEN-LAST:event_pedraRadActionPerformed

    private void papelRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papelRadActionPerformed
        tesouraRad.setSelected(false);
        pedraRad.setSelected(false);
        
        Random rn = new Random();
        int resposta = rn.nextInt(3);
                      
        if (papelRad.isSelected() && resposta == 0) {
                          
            JOptionPane.showMessageDialog(this, "Tirei papel, empatamos =|");
            }
        else if (papelRad.isSelected() && resposta == 1) {
                          
            JOptionPane.showMessageDialog(this, "Tirei pedra, parece que você ganhou =(");
            }
        else if (papelRad.isSelected() && resposta == 2) {
                          
            JOptionPane.showMessageDialog(this, "Tirei tesoura, ganhei de você =D");
            }   
        
    }//GEN-LAST:event_papelRadActionPerformed

    private void tesouraRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesouraRadActionPerformed
        pedraRad.setSelected(false);
        papelRad.setSelected(false);
        
        Random rn = new Random();
        int resposta = rn.nextInt(3);
                      
        if (tesouraRad.isSelected() && resposta == 0) {
                          
            JOptionPane.showMessageDialog(this, "Tirei Papel, ganhou de mim =\\");
            }
        else if (tesouraRad.isSelected() && resposta == 1) {
                          
            JOptionPane.showMessageDialog(this, "Tirei pedra, Ganhei de você ;D");
            }
        else if (tesouraRad.isSelected() && resposta == 2) {
                          
            JOptionPane.showMessageDialog(this, "Tirei tesoura também, empatamos!");
            }
    }//GEN-LAST:event_tesouraRadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedraPapelTesoura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton papelRad;
    private javax.swing.JRadioButton pedraRad;
    private javax.swing.JRadioButton tesouraRad;
    // End of variables declaration//GEN-END:variables

    private void JOptinPaneShowMessageDialog(String o_computador_escolheu_TESOURA) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
